INHERIT: mkdocs-base.yaml
site_name: "GitLab CI + Dynatrace — Hands-On Enablement"
repo_name: "View Code on GitHub"
repo_url: "https://github.com/domuharahap/dynatrace-gitlab-runner-enablement"
nav:
  - 'About': index.md
  - 'Getting Started': getting-started.md
  - 'Use Case 1 — First GitLab Project & Runner': usecase1-gitlabrunner.md
  - 'Use Case 2 — Node.js CI, Test & SAST': usecase2-nodejs-sast.md
  - 'Use Case 3 — Docker Build & Deploy to K8s': usecase3-deployk8s.md
  - 'Use Case 4 — Dynatrace Events & Load Testing': usecase4-dynatrace.md
  - 'Use Case 5 — Dev/Prod Gates': usecase5-devprodstages.md
  - 'Use Case 6 — Site Reliability Guardian & Automated Rollback': usecase6-srg-workflow.md
  - 'Cleanup': cleanup.md
  - 'Resources': resources.md
  - "What's Next": whats-next.md
extra:
  rum_snippet: ""
